SSS - S3 Toolkit: XMLOStream Class Reference
XMLOStream Class Reference
Parsing
XMLGenerator. Use methods or overloaded subscript operator to insert data into XML tree.
#include <xmlstreams.h>
Public Types
enum MoveAction { UP , DOWN , REWIND }
Move up or down one level in tree or rewind to root.
Public Member Functions
void Up (int level=1)
void Down ()
void Rewind ()
Move pointer to current node to root.
XMLOStream & InsertText (const std::string &text)
XMLOStream & Insert (const std::string &s)
XMLOStream & Move (MoveAction a, int level=1)
XMLOStream & operator[] (const std::string &s)
XMLOStream & operator[] (MoveAction a)
Invoke Insert(MoveAction) method.
XMLOStream (tinyxml2::XMLDocument &d)
XMLOStream & operator= (const std::string &s)
std::string XMLText () const
const tinyxml2::XMLDocument & GetDocument () const
Detailed Description
XMLGenerator. Use methods or overloaded subscript operator to insert data into XML tree.
A XML document object and a pointer to the current XML Element are maintained inside the class instance. Elements are added under the current element. The current element pointer can be moved up or down the tree as needed. The generated XML code is extracted by calling the XMLText method.
Example
Generating the ACL request body.
Request format:
<AccessControlPolicy>
   <Owner>
      <DisplayName>string</DisplayName>
      <ID>string</ID>
   </Owner>
   <AccessControlList>
      <Grant>
         <Grantee>
            <DisplayName>string</DisplayName>
            <EmailAddress>string</EmailAddress>
            <ID>string</ID>
            <xsi:type>string</xsi:type>
            <URI>string</URI>
         </Grantee>
         <Permission>string</Permission>
      </Grant>
   </AccessControlList>
</AccessControlPolicy>
Code:
std::string GenerateAclXML(const AccessControlPolicy &acl) {
  XMLDocument doc;
  XMLOStream os(doc);
  os["accesscontrolpolicy/accesscontrollist"];
  if (!acl.ownerDisplayName.empty() || !acl.ownerID.empty()) {
    os["owner"]; // <accesscontrolpolicy><accesscontrollist><owner>
    if (!acl.ownerDisplayName.empty()) {
      //<accesscontrolpolicy><accesscontrollist><owner><displayname>
      os["displayname"] = acl.ownerDisplayName;
      //</displayname> automatically move to upper level after assignment
    }
    if (!acl.ownerID.empty()) {
      //<accesscontrolpolicy><accesscontrollist><owner><ownerid>
      os["ownerid"] = acl.ownerDisplayName;
      //</ownerid> automatically move to upper level after assignment
    }
    os["/"]; // </owner>
  }
  for (const auto &g : acl.grants) {
    if (g.permission.empty()) {
      throw logic_error("Missing required field 'permission'");
    }
    os["grant"]; // <grant>
    const Grant::Grantee &i = g.grantee;
    if (!i.Empty()) {
      os["grantee"]; // <grant><grantee>
      if (!i.displayName.empty()) {
        // <grant><grantee><displayname>
        os["displayname"] = i.displayName;
        // </displayname>
      }
      if (!i.emailAddress.empty()) {
        // <grant><grantee><emailaddress>
        os["emailaddress"] = i.emailAddress;
        // </emailaddress>
      }
      if (!i.id.empty()) {
        // <grant><grantee><id>
        os["id"] = i.id;
        // </id>
      }
      if (!i.xsiType.empty()) {
        // <grant><grantee><type>``
        os["type"] = i.xsiType;
        // </type>
      }
      if (!i.uri.empty()) {
        // <grant><grantee><uri>
        os["uri"] = i.uri;
        // <uri>
      }
    }
    os["/"] // </grantee>
            // <grant><permission>
      ["permission"] = g.permission;
    // </permission>
  }
  return os.XMLText();
}
Definition at line 125 of file xmlstreams.h.
Constructor & Destructor Documentation
XMLOStream()
XMLOStream::XMLOStream (tinyxml2::XMLDocument & d) inline
Constructor: requires a reference to a pre-existing XML document.
Parameters
[in] d wrapped XML document
Definition at line 230 of file xmlstreams.h.
 : doc_(d) {}
Member Function Documentation
Down()
void XMLOStream::Down () inline
Move down after setting text Set down_ flag: pointer to current node will be moved to child after next insertion
Definition at line 144 of file xmlstreams.h.
 { down_ = true; }
GetDocument()
const tinyxml2::XMLDocument& XMLOStream::GetDocument () const inline
Returns
reference to current document
Definition at line 242 of file xmlstreams.h.
 { return doc_; }
Insert()
XMLOStream& XMLOStream::Insert (const std::string & s) inline
Insert XML element under current XML element.
Parameters
[in] s tag name
Returns
reference to current XMLOStream instance
Definition at line 166 of file xmlstreams.h.
{
     std::vector<std::string> elems;
     std::istringstream is(s);
     for (std::string buf; std::getline(is, buf, '/');) {
       if (!buf.empty()) {
         elems.push_back(buf);
       }
     }
     if (elems.empty())
       return *this;
     auto pe = cur_;
     if (!cur_) {
       cur_ = doc_.NewElement(elems.front().c_str());
       doc_.InsertFirstChild(cur_);
       pe = cur_;
     } else {
       pe = cur_->InsertNewChildElement(s.c_str());
     }
     for (auto e = ++begin(elems); e != end(elems); ++e) {
       pe = pe->InsertNewChildElement(e->c_str());
     }
     if (down_) {
       cur_ = pe;
       down_ = false;
     }
     return *this;
   }
InsertText()
XMLOStream& XMLOStream::InsertText (const std::string & text) inline
Insert text inside current element.
Parameters
[in] text text to insert
Returns
reference to current XMLOStream instance, will return without inserting in case current pointer to XML element is NULL
Definition at line 157 of file xmlstreams.h.
{
     if (!cur_)
       return *this;
     cur_->SetText(text.c_str());
     return *this;
   }
Move()
XMLOStream& XMLOStream::Move (MoveAction a, int level = 1) inline
Move pointer to XML element.
See also
MoveAction In the case of REWIND or UP the action is executed immediately in case of DOWN it is executed after next insertion operation
Definition at line 197 of file xmlstreams.h.
{
     switch (a) {
     case UP:
       Up(level);
       break;
     case DOWN:
       Down();
       break;
     case REWIND:
       Rewind();
       break;
     default:
       break;
     }
     return *this;
   }
References Down(), Rewind(), and Up().
operator=()
XMLOStream& XMLOStream::operator= (const std::string & s) inline
Add text element to current XML element and move up one level.
Parameters
[in] s text to insert
Returns
reference to XMLOStream instance
Definition at line 234 of file xmlstreams.h.
{
     InsertText(s);
     Up();
     return *this;
   }
References InsertText(), and Up().
operator[]()
XMLOStream& XMLOStream::operator[] (const std::string & s) inline
Invokes insert method forcing DOWN action after insert. In case only path separator ('/') elements are provided the UP action is invoked as many times as there are '/' caracters in the string.
Definition at line 218 of file xmlstreams.h.
{
     if (all_of(begin(s), end(s), [](auto c) { return c == '/'; })) {
       Up(s.size());
       return *this;
     }
     down_ = true;
     return Insert(s);
   }
References Insert(), and Up().
Up()
void XMLOStream::Up (int level = 1) inline
Move up
Parameters
[in] level number of parents to traverse, default is one
Definition at line 131 of file xmlstreams.h.
{
     if (!cur_) {
       throw std::logic_error("Cannot pop, Null element");
     }
     if (!cur_->Parent()) {
       throw std::logic_error("Cannot pop, Null parent");
     }
     for (; level; cur_ = cur_->Parent()->ToElement(), level--)
       ;
   }
XMLText()
std::string XMLOStream::XMLText () const inline
Returns
current content of XML document as XML text
Definition at line 240 of file xmlstreams.h.
 { return XMLToText(doc_, true, 0, 0); }
References XMLToText().
The documentation for this class was generated from the following file:
/home/ugovaretto/projects/uv-cpp/s3client/repo/lib/include/xmlstreams.h