SSS - S3 Toolkit: sss::WebClient Class Reference
sss::WebClient Class Reference
Send web requests through libcurl.
#include <webclient.h>
Public Types
using WriteFunction = size_t(*)(char *data, size_t size, size_t nmemb, void *writerData)
using ReadFunction = size_t(*)(void *ptr, size_t size, size_t nmemb, void *readerData)
Public Member Functions
WebClient (const WebClient &)=delete
Disable copy constructor: only one libcurl handle per thread allwed.
WebClient (WebClient &&other)
Move constructor.
WebClient ()
Default constructor. First instance initializes libcurl.
WebClient (const std::string &url)
Constructor initializing only URL.
WebClient (const std::string &endPoint, const std::string &path, const std::string &method="GET", const Map &params=Map(), const Map headers=Map())
~WebClient ()
Destructor. Last instance cleans up libcurl.
bool Send ()
bool SSLVerify (bool verifyPeer, bool verifyHost=true)
bool SetUrl (const std::string &url)
void SetEndpoint (const std::string &ep)
Set endpoint: <proto>://<server>:<port>
void SetPath (const std::string &path)
void SetHeaders (const Map &headers)
void SetReqParameters (const Map &params)
void SetMethod (const std::string &method, size_t size=0)
void SetUrlEncodedPostData (const Map &postData)
void SetUrlEncodedPostData (const std::string &postData)
void SetPostData (const std::string &data)
long StatusCode () const
const std::string & GetUrl () const
const std::vector< char > & GetResponseBody () const
const std::vector< char > & GetResponseHeader () const
std::string GetContentText () const
Get response body as text.
std::string GetHeaderText () const
bool SetWriteFunction (WriteFunction f, void *userData)
bool SetReadFunction (ReadFunction f, void *userData)
bool UploadFile (const std::string &fname, size_t fsize=0)
Upload file.
bool UploadFile (const std::string &fname, size_t offset, size_t size)
Upload file starting from offset.
bool UploadFileUnbuffered (const std::string &fname, size_t offset, size_t size)
Upload file starting from offset using unbuffered I/O read.
bool UploadFileMM (const std::string &fname, size_t offset, size_t size)
Upload file starting from offset using unbuffered memory mapping of file.
bool UploadDataFromBuffer (const char *data, size_t offset, size_t size)
Upload data from memory buffer.
std::string ErrorMsg () const
CURLcode SetOpt (CURLoption option, va_list argp)
Passthrough to curl_easy_setopt.
CURLcode GetInfo (CURLINFO info, va_list argp)
Passthrough method to curl_easy_getinfo.
void SetVerbose (bool verbose)
Send verbose output to stderr or the stream mapped to CURLOPT_STDERR.
bool RedirectSTDErr (FILE *f)
Redirect stderr to file. Returns false when it fails.
void ClearBuffers ()
Clear internal buffers.
void ResetRWFunctions ()
Reset read/write functions to default.
Detailed Description
Send web requests through libcurl.
Configure state then invoke WebClient::Send to send request.
Retrieve data through:
GetResponseBody()
GetResponseHeader()
GetContentText()
GetHeaderText()
Error handling is managed by having libcurl log errors into a char buffer. When a method fails returning false, you can extract the error message by invoking the WebClient::ErrorMsg() method.
Usage
WebClient req;
req.SSLVerify(verifyPeer, verifyHost);
req.SetEndpoint(args.endpoint);
req.SetPath(path);
req.SetMethod(args.method);
req.SetReqParameters(args.params);
req.SetHeaders(headers);
FILE *of = NULL;
if (!args.outfile.empty()) {
  of = fopen(args.outfile.c_str(), "wb");
  req.SetWriteFunction(NULL, of); // default is to write to file
}
if (!args.data.empty()) {
  if (!args.dataIsFileName) {
    if (ToLower(args.method) == "post") {
      req.SetUrlEncodedPostData(ParseParams(args.data.data()));
      req.SetMethod("POST");
      req.Send();
    } else { // "put"
      req.UploadDataFromBuffer(args.data.data(), 0, args.data.size());
    }
  } else {
    if (ToLower(args.method) == "put") {
      req.UploadFile(args.data.data());
    } else if (args.method == "post") {
      ifstream t(args.data.data());
      const string str((istreambuf_iterator<char>(t)),
                       istreambuf_iterator<char>());
      req.SetMethod("POST");
      req.SetPostData(str);
      req.Send();
    } else {
      throw domain_error("Wrong method " + args.method);
    }
  }
} else
  req.Send();
if (of)
  fclose(of);
return req;
Definition at line 125 of file webclient.h.
Member Typedef Documentation
ReadFunction
using sss::WebClient::ReadFunction = size_t (*)(void *ptr, size_t size, size_t nmemb, void *readerData)
Function type invoked by libcurl to read data to send
Parameters
[in] nmemb number of blocks of size size
[in] readerData user data passed to reade function
Definition at line 135 of file webclient.h.
WriteFunction
using sss::WebClient::WriteFunction = size_t (*)(char *data, size_t size, size_t nmemb, void *writerData)
Function type invoked by libcurl to write received data
Parameters
[in] nmemb number of blocks of size size
[in] writerData user data passed to write function
Definition at line 130 of file webclient.h.
Constructor & Destructor Documentation
WebClient()
sss::WebClient::WebClient (const std::string & endPoint, const std::string & path, const std::string & method = "GET", const Map & params = Map(), const Map headers = Map()) inline
Constructor
Parameters
[in] endPoint endpoint in the format <proto>://<server>:port
[in] path path to be added to endPoint to compete URL: /.../...
[in] method HTTP method
[in] params key,value map of parameters k1=value1&k2=value2&...
Definition at line 172 of file webclient.h.
       : endpoint_(endPoint), path_(path), method_(method), params_(params),
         headers_(headers) {
     InitEnv();
   }
~WebClient()
sss::WebClient::~WebClient ()
Destructor. Last instance cleans up libcurl.
Cleanup and invoke cleanup on libcurl in case of last instance.
Definition at line 148 of file webclient.cpp.
                       {
   if (curlHeaderList_) {
     curl_slist_free_all(curlHeaderList_);
   }
   if (curl_) { // current object could have been moved
     // libcurl init and cleanup functions ar NOT thread safe and the
     // behaviour is unpredictable in case of use in a multithreaded
     // environment, this just guarantees that there is only a single
     // call to curl_global_cleanup
     curl_easy_cleanup(curl_);
     const std::lock_guard<std::mutex> lock(cleanupMutex_);
     --numInstances_;
     if (numInstances_ == 0)
       curl_global_cleanup();
   }
 }
Member Function Documentation
ErrorMsg()
std::string sss::WebClient::ErrorMsg () const
Return curl error.
Returns
libcurl error as returned by curl_easy_strerror or curl_multi_strerror.
Definition at line 416 of file webclient.cpp.
 { return errorBuffer_.data(); }
GetHeaderText()
std::string sss::WebClient::GetHeaderText () const
Get headers as text.
Returns
response headers as a single string.
Definition at line 437 of file webclient.cpp.
{
   std::vector<char> header = GetResponseHeader();
   return std::string(begin(header), end(header));
 }
References GetResponseHeader().
GetInfo()
CURLcode sss::WebClient::GetInfo (CURLINFO info, va_list argp)
Passthrough method to curl_easy_getinfo.
https://curl.se/libcurl/c/curl_easy_getinfo.html
Definition at line 424 of file webclient.cpp.
{
   return curl_easy_getinfo(curl_, info, argp);
 }
GetResponseBody()
const std::vector< char > & sss::WebClient::GetResponseBody () const
Get response content.
Returns
response bytes (char used because it's the type used within libcurl)
Definition at line 270 of file webclient.cpp.
{
   return writeBuffer_.data;
 }
GetResponseHeader()
const std::vector< char > & sss::WebClient::GetResponseHeader () const
Get reponse header.
Returns
raw response headers as a single byte array.
Definition at line 274 of file webclient.cpp.
{
   return headerBuffer_;
 }
GetUrl()
const std::string & sss::WebClient::GetUrl () const
Return full URL.
Returns
endpoint + url parameters
Definition at line 268 of file webclient.cpp.
 { return url_; }
Send()
bool sss::WebClient::Send ()
Send request.
Returns
false if error, retrieve error message through WebClient::ErroMsg
Definition at line 165 of file webclient.cpp.
                      {
   const bool ret = Status(curl_easy_perform(curl_));
   curl_easy_getinfo(curl_, CURLINFO_RESPONSE_CODE, &responseCode_);
   return ret;
 }
SetHeaders()
void sss::WebClient::SetHeaders (const Map & headers)
Store headers into internal buffer.
Parameters
[in] headers HTTP headers
Definition at line 202 of file webclient.cpp.
{
   headers_ = headers;
   if (curlHeaderList_) {
     curl_slist_free_all(curlHeaderList_);
     curlHeaderList_ = NULL;
   }
   if (!headers_.empty()) {
     for (auto kv : headers_) {
       curlHeaderList_ = curl_slist_append(
           curlHeaderList_, (kv.first + ": " + kv.second).c_str());
     }
   }
   curl_easy_setopt(curl_, CURLOPT_HTTPHEADER, curlHeaderList_);
 }
SetMethod()
void sss::WebClient::SetMethod (const std::string & method, size_t size = 0)
Set HTTP method.
Parameters
[in] method "GET", "POST", "PUT", "DELETE", "HEAD"
Definition at line 222 of file webclient.cpp.
{
   method_ = ToUpper(method);
   if (method_ == "GET") {
     curl_easy_setopt(curl_, CURLOPT_UPLOAD, 0L);
     curl_easy_setopt(curl_, CURLOPT_NOBODY, 0L);
     curl_easy_setopt(curl_, CURLOPT_HTTPGET, 1L);
   } else if (method == "HEAD") {
     curl_easy_setopt(curl_, CURLOPT_UPLOAD, 0L);
     curl_easy_setopt(curl_, CURLOPT_NOBODY, 1L);
     curl_easy_setopt(curl_, CURLOPT_CUSTOMREQUEST, "HEAD");
   } else if (method == "DELETE") {
     curl_easy_setopt(curl_, CURLOPT_UPLOAD, 0L);
     curl_easy_setopt(curl_, CURLOPT_CUSTOMREQUEST, "DELETE");
   } else if (method == "POST") {
     curl_easy_setopt(curl_, CURLOPT_UPLOAD, 0L);
     curl_easy_setopt(curl_, CURLOPT_CUSTOMREQUEST, "POST");
     curl_easy_setopt(curl_, CURLOPT_POSTFIELDSIZE, urlEncodedPostData_.size());
     curl_easy_setopt(curl_, CURLOPT_POSTFIELDS, urlEncodedPostData_.c_str());
   } else if (method_ == "PUT") {
     curl_easy_setopt(curl_, CURLOPT_UPLOAD, 1L);
     curl_easy_setopt(curl_, CURLOPT_INFILESIZE_LARGE, size);
     //@warining: never set method to "PUT" when specifying CURLOPT_UPLOAD
     // because it will trigger an additional PUT request
   }
 }
SetOpt()
CURLcode sss::WebClient::SetOpt (CURLoption option, va_list argp)
Passthrough to curl_easy_setopt.
https://curl.se/libcurl/c/curl_easy_setopt.html
Definition at line 419 of file webclient.cpp.
{
   return curl_easy_setopt(curl_, option, argp);
 }
SetPath()
void sss::WebClient::SetPath (const std::string & path)
Set URL path.
Parameters
[in] path URL with endpoint part removed.
Definition at line 197 of file webclient.cpp.
{
   path_ = path;
   BuildURL();
 }
SetPostData()
void sss::WebClient::SetPostData (const std::string & data)
Store data to be posted.
Parameters
[in] data text to be posted.
Definition at line 261 of file webclient.cpp.
{
   curl_easy_setopt(curl_, CURLOPT_POSTFIELDSIZE, data.size());
   curl_easy_setopt(curl_, CURLOPT_COPYPOSTFIELDS, data.c_str());
 }
SetReadFunction()
bool sss::WebClient::SetReadFunction (ReadFunction f, void * userData)
Set function libcurl uses to read data to send.
Parameters
[in] f pointer to function called by libcurl to read data to send; set to NULL to read from file.
[in] userData pointer to user data.
Definition at line 286 of file webclient.cpp.
{
   if (curl_easy_setopt(curl_, CURLOPT_READFUNCTION, f) != CURLE_OK)
     return false;
   if (curl_easy_setopt(curl_, CURLOPT_READDATA, ptr) != CURLE_OK)
     return false;
   return true;
 }
SetReqParameters()
void sss::WebClient::SetReqParameters (const Map & params)
Store request parameters into internal buffer.
Parameters
[in] params URL parameters: key=value&...
Definition at line 217 of file webclient.cpp.
{
   params_ = params;
   BuildURL();
 }
SetUrl()
bool sss::WebClient::SetUrl (const std::string & url)
Set full URL
Parameters
[in] url endpoint + paramters URL
Definition at line 181 of file webclient.cpp.
{
   url_ = url;
   const auto res = curl_easy_setopt(curl_, CURLOPT_URL, url_.c_str());
   if (res != CURLE_OK) {
     throw runtime_error(string("Error setting URL - ") +
                         curl_easy_strerror(res));
   }
   //@todo return void!
   return true;
 }
SetUrlEncodedPostData() [1/2]
void sss::WebClient::SetUrlEncodedPostData (const Map & postData)
Url-encode and store data to be posted from {key,value} map.
Parameters
[in] postData {key, value} map of URL paramters.
Definition at line 249 of file webclient.cpp.
{
   urlEncodedPostData_ = UrlEncode(postData);
   curl_easy_setopt(curl_, CURLOPT_POSTFIELDSIZE, urlEncodedPostData_.size());
   curl_easy_setopt(curl_, CURLOPT_COPYPOSTFIELDS, urlEncodedPostData_.c_str());
 }
References sss::UrlEncode().
SetUrlEncodedPostData() [2/2]
void sss::WebClient::SetUrlEncodedPostData (const std::string & postData)
Url-encode and store data to be posted from string in the standard key=value&key2=value2... format.
Parameters
[in] postData "key1=value1&key2=value2..."
Definition at line 255 of file webclient.cpp.
{
   urlEncodedPostData_ = UrlEncode(postData);
   curl_easy_setopt(curl_, CURLOPT_POSTFIELDSIZE, urlEncodedPostData_.size());
   curl_easy_setopt(curl_, CURLOPT_COPYPOSTFIELDS, urlEncodedPostData_.c_str());
 }
References sss::UrlEncode().
SetWriteFunction()
bool sss::WebClient::SetWriteFunction (WriteFunction f, void * userData)
Set function libcurl uses to store response data.
Parameters
[in] f pointer to function called by libcurl to consume returned data.
[in] userData pointer to user data.
Definition at line 278 of file webclient.cpp.
{
   if (curl_easy_setopt(curl_, CURLOPT_WRITEFUNCTION, f) != CURLE_OK)
     return false;
   if (curl_easy_setopt(curl_, CURLOPT_WRITEDATA, ptr) != CURLE_OK)
     return false;
   return true;
 }
SSLVerify()
bool sss::WebClient::SSLVerify (bool verifyPeer, bool verifyHost = true)
Set SSL verification options: peer and/or host Verification should be disabled when sending https requests through SSH tunnels.
Parameters
[in] verifyPeer verify the authenticity of the peer's certificate
[in] verifyHost verify the identity of the server
Definition at line 173 of file webclient.cpp.
{
   return Status(curl_easy_setopt(curl_, CURLOPT_SSL_VERIFYPEER,
                                  verifyPeer ? 1L : 0L)) &&
          Status(curl_easy_setopt(curl_, CURLOPT_SSL_VERIFYHOST,
                                  verifyHost ? 1L : 0L));
 }
StatusCode()
long sss::WebClient::StatusCode () const
Return status code from last executed request.
Returns
HTTP status (20*, 30*, 40*, 50*).
Definition at line 266 of file webclient.cpp.
 { return responseCode_; }
UploadDataFromBuffer()
bool sss::WebClient::UploadDataFromBuffer (const char * data, size_t offset, size_t size)
Upload data from memory buffer.
Parameters
[in] data pointer to data
[in] offset offset
[in] size data size
Returns
true if successful, false otherwise
Definition at line 314 of file webclient.cpp.
{
   if (size == 0)
     return true;
   if (curl_easy_setopt(curl_, CURLOPT_READFUNCTION, MemReader) != CURLE_OK) {
     throw std::runtime_error("Cannot set curl read function");
   }
   if (curl_easy_setopt(curl_, CURLOPT_READDATA, &refBuffer_) != CURLE_OK) {
     throw std::runtime_error("Cannot set curl read data buffer");
   }
   refBuffer_.data = data;
   refBuffer_.offset = offset;
   refBuffer_.size = size;
   SetMethod("PUT", size);
   return Send();
 }
References Send(), and SetMethod().
UploadFile() [1/2]
bool sss::WebClient::UploadFile (const std::string & fname, size_t fsize = 0)
Upload file.
Parameters
[in] fname file name
[in] fsize file size, if zero file size will be computed
Returns
true if successful, false otherwise
Definition at line 294 of file webclient.cpp.
{
   const size_t size = fsize ? fsize : FileSize(fname);
   FILE *file = fopen(fname.c_str(), "rb");
   if (!file) {
     throw std::runtime_error("Cannot open file " + fname);
   }
   auto _ = CloseFile(file);
   // when read function is NULL the passed void* is interpreted as
   // a FILE* by libcurl
   if (!SetReadFunction(NULL, file)) {
     throw std::runtime_error("Cannot set read function");
   }
   SetMethod("PUT", size);
   const bool result = Send();
   if (!result) {
     throw std::runtime_error("Error sending request: " + ErrorMsg());
   }
   return result;
 }
References ErrorMsg(), Send(), SetMethod(), and SetReadFunction().
UploadFile() [2/2]
bool sss::WebClient::UploadFile (const std::string & fname, size_t offset, size_t size)
Upload file starting from offset.
Parameters
[in] fname file name
[in] offset offset
[in] size file size, if zero size is computed from file.
Returns
true if successful, false otherwise
Definition at line 331 of file webclient.cpp.
{
   size = size ? size : FileSize(fname);
   if (!size) {
     throw runtime_error("Cannot compute file size for file " + fname);
   }
   FILE *file = fopen(fname.c_str(), "rb");
   if (!file) {
     throw std::runtime_error("Cannot open file " + fname);
   }
   if (fseek(file, offset, SEEK_SET)) {
     throw std::runtime_error("Cannot move file pointer");
   }
   FileInfo fi{file, size};
   if (!SetReadFunction(ReadFile, &fi)) {
     throw std::runtime_error("Cannot set read function");
   }
   SetMethod("PUT", size);
   const bool result = Send();
   if (!result) {
     throw std::runtime_error("Error sending request: " + ErrorMsg());
   }
   return result;
 }
References ErrorMsg(), sss::ReadFile(), Send(), SetMethod(), and SetReadFunction().
UploadFileMM()
bool sss::WebClient::UploadFileMM (const std::string & fname, size_t offset, size_t size)
Upload file starting from offset using unbuffered memory mapping of file.
Parameters
[in] fname file name
[in] offset offset
[in] size file size, if zero it will compute file size on its ow
Returns
true if successful, false otherwise
Definition at line 384 of file webclient.cpp.
{
 #ifndef __APPLE__
   int fd = open(fname.c_str(), O_RDONLY | O_LARGEFILE);
 #else
   int fd = open(fname.c_str(), O_RDONLY);
 #endif
   if (fd < 0) {
     throw std::runtime_error("Error cannot open input file: " +
                              std::string(strerror(errno)));
     exit(EXIT_FAILURE);
   }
   auto _ = CloseFileDesc(fd);
   char *src = (char *)mmap(NULL, size, PROT_READ, MAP_PRIVATE, fd, offset);
   if (src == MAP_FAILED) { // mmap returns (void *) -1 == MAP_FAILED
     throw std::runtime_error("Error mapping memory: " +
                              std::string(strerror(errno)));
     exit(EXIT_FAILURE);
   }
   if (!UploadDataFromBuffer(src, 0, size)) {
     throw std::runtime_error("Error uploading memory mapped data");
     exit(EXIT_FAILURE);
   }
   if (munmap(src, size)) {
     throw std::runtime_error("Error unmapping memory: " +
                              std::string(strerror(errno)));
     exit(EXIT_FAILURE);
   }
   return true;
 }
References UploadDataFromBuffer().
UploadFileUnbuffered()
bool sss::WebClient::UploadFileUnbuffered (const std::string & fname, size_t offset, size_t size)
Upload file starting from offset using unbuffered I/O read.
Parameters
[in] fname file name
[in] offset offset
[in] size file size, if zero size will be computer as (file size) - offset.
Returns
true if successful, false otherwise
Definition at line 357 of file webclient.cpp.
{
 #ifndef __APPLE__
   int file = open(fname.c_str(), S_IRGRP | O_LARGEFILE);
 #else
   int file = open(fname.c_str(), S_IRGRP);
 #endif
   if (file < 0) {
     throw std::runtime_error(strerror(errno));
   }
   auto _ = CloseFileDesc(file);
   if (lseek(file, offset, SEEK_SET) < 0) {
     throw std::runtime_error(strerror(errno));
   }
   FileDescInfo fi{file, size};
   if (!SetReadFunction(ReadFileUnbuffered, &fi)) {
     throw std::runtime_error("Cannot set read function");
   }
   SetMethod("PUT", size);
   const bool result = Send();
   if (!result) {
     throw std::runtime_error("Error sending request: " + ErrorMsg());
     close(file);
   }
   return result;
 }
References ErrorMsg(), Send(), SetMethod(), and SetReadFunction().
The documentation for this class was generated from the following files:
/home/ugovaretto/projects/uv-cpp/s3client/repo/lib/include/webclient.h
/home/ugovaretto/projects/uv-cpp/s3client/repo/lib/src/webclient.cpp