var hierarchy =
[
    [ "sss::api::AccessControlPolicy", "structsss_1_1api_1_1AccessControlPolicy.html", null ],
    [ "sss::api::BucketInfo", "structsss_1_1api_1_1BucketInfo.html", null ],
    [ "sss::BucketValidation", "structsss_1_1BucketValidation.html", null ],
    [ "sss::ComputeSignatureConfig", "structsss_1_1ComputeSignatureConfig.html", null ],
    [ "sss::api::Grant", "structsss_1_1api_1_1Grant.html", null ],
    [ "sss::api::Grant::Grantee", "structsss_1_1api_1_1Grant_1_1Grantee.html", null ],
    [ "sss::api::S3Api::ListObjectV2Config", "structsss_1_1api_1_1S3Api_1_1ListObjectV2Config.html", null ],
    [ "sss::api::S3Api::ListObjectV2Result", "structsss_1_1api_1_1S3Api_1_1ListObjectV2Result.html", null ],
    [ "Params", "structParams.html", null ],
    [ "sss::api::S3Api", "classsss_1_1api_1_1S3Api.html", null ],
    [ "sss::S3ClientConfig", "structsss_1_1S3ClientConfig.html", null ],
    [ "sss::S3Credentials", "structsss_1_1S3Credentials.html", null ],
    [ "sss::S3DataTransferConfig", "structsss_1_1S3DataTransferConfig.html", null ],
    [ "sss::S3SignUrlConfig", "structsss_1_1S3SignUrlConfig.html", null ],
    [ "sss::api::S3Api::SendParams", "structsss_1_1api_1_1S3Api_1_1SendParams.html", null ],
    [ "sss::Signature", "structsss_1_1Signature.html", null ],
    [ "sss::SplitIterator", "classsss_1_1SplitIterator.html", null ],
    [ "sss::SplitRange", "classsss_1_1SplitRange.html", null ],
    [ "TempFile", "structTempFile.html", null ],
    [ "sss::Time", "structsss_1_1Time.html", null ],
    [ "sss::URL", "structsss_1_1URL.html", null ],
    [ "sss::WebClient", "classsss_1_1WebClient.html", null ],
    [ "XMLIStream", "classXMLIStream.html", null ],
    [ "XMLOStream", "classXMLOStream.html", null ],
    [ "XMLVisitor", null, [
      [ "DOMToDictVisitor", "classDOMToDictVisitor.html", null ],
      [ "DOMToDictVisitor", "classDOMToDictVisitor.html", null ],
      [ "FindVisitor", "classFindVisitor.html", null ],
      [ "FindVisitor", "classFindVisitor.html", null ],
      [ "MultiPathVisitor", "classMultiPathVisitor.html", null ],
      [ "MultiPathVisitor", "classMultiPathVisitor.html", null ],
      [ "MultiVisitor", "classMultiVisitor.html", null ],
      [ "MultiVisitor", "classMultiVisitor.html", null ],
      [ "PathVisitor", "classPathVisitor.html", null ],
      [ "PathVisitor", "classPathVisitor.html", null ],
      [ "ToTextVisitor", "classToTextVisitor.html", null ],
      [ "ToTextVisitor", "classToTextVisitor.html", null ]
    ] ]
];