SSS - S3 Toolkit: /Users/ugo/projects/s3client/repo/lib/include/utility.h File Reference
utility.h File Reference
internal utility functions
#include <algorithm>
#include <functional>
#include <string>
#include <unordered_map>
Data Structures
class sss::SplitIterator
Iterator over splits.
class sss::SplitRange
Range over splits.
Functions
template<class ContainerT >
void sss::Split (const std::string &str, ContainerT &cont, const std::string &delims=" ", const size_t count=std::string::npos)
auto sss::begin (const SplitRange &sr)
return iterator at start position
auto sss::end (const SplitRange &sr)
return iterator at end position
int sss::RandomIndex (int lowerBound, int upperBound)
size_t sss::FileSize (const std::string &filename)
Toml sss::ParseTomlFile (const std::string &filename)
std::string sss::GetHomeDir ()
void sss::TrimLine (std::string &s)
std::string sss::ToUpper (std::string s)
std::string sss::ToLower (std::string s)
Detailed Description
internal utility functions
Function Documentation
FileSize()
size_t sss::FileSize (const std::string & filename)
Return file size
Parameters
filename file name
Returns
file size in number of bytes
References sss::FileSize().
GetHomeDir()
std::string sss::GetHomeDir ()
Return home directory
Returns
home directory path
References sss::GetHomeDir().
ParseTomlFile()
Toml sss::ParseTomlFile (const std::string & filename)
Parse Toml file in AWS format and return tree as map of maps
Works with AWS format (nested s'=') Parent key is added added to child key: <parent key>/<child_key>'
Parameters
filename location of configuration file
Returns
Toml content
References sss::GetHomeDir(), and sss::ParseTomlFile().
RandomIndex()
int sss::RandomIndex (int lowerBound, int upperBound)
Return integer in [low,high] range
Parameters
lowerBound lower bound
upperBound upper bound
Returns
random value in interval [lowerBound, upperBound]
References sss::RandomIndex().
Split()
template<class ContainerT > void sss::Split (const std::string & str, ContainerT & cont, const std::string & delims = " ", const size_t count = std::string::npos)
Split string and put substrings into container
Parameters
[in] str input text
[out] cont container with push_back() method
[in] delims delimiter
[in] count number of delimiters to parse
References sss::Split().
ToLower()
std::string sss::ToLower (std::string s)
Convert to lowercase
Parameters
s text
Returns
lowercase text
References sss::ToLower().
ToUpper()
std::string sss::ToUpper (std::string s)
Convert to uppercase text
Parameters
s text
Returns
uppercase text
References sss::ToUpper().
TrimLine()
void sss::TrimLine (std::string & s)
Remove leading '#' and leading and trailing blanks in place
References sss::TrimLine().